# Generated by Django 4.0.4 on 2022-05-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_start', models.DateTimeField(auto_now_add=True)),
                ('dttm_end', models.DateTimeField(blank=True, null=True)),
                ('answers', models.TextField(default='[]')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Test.testinfo')),
            ],
        ),
    ]
